### ISSUE TITLE
Extension does not always generate .class files

### ISSUE THREAD

**Issue by holly-cummins** [holly-cummins/bon-jova-rockstar-implementation#10]
Although @hannotify sees class files reliably being generated by the extension, @holly-cummins does not. Even for @hannotify, there's a need to visit localhost first, which isn't ideal, and the files are missing a .class extension. 

This issue covers 
- Adding the .class extension
- Eagerly compiling, so there's no need to visit localhost (this may not be needed if we add app unit tests, since running the unit test would drive the compile)
- Resolving the discrepancy in behaviour between what Hanno sees and what Holly sees

**Comment by hannotify** [comment]
If we go the 'unit test' route, we can configure Quarkus to automatically run the tests after startup by adding `quarkus.test.continuous-testing=enabled` to `application.properties`.

**Comment by hannotify** [comment]
Tested this scenario and it turns out the `*.rock` files only get compiled after at least one edit. So I need to find a way to trigger the compilation step without having to manually edit the rock file.

**Comment by holly-cummins** [comment]
Ah, yes, I can get the `.class` files to appear if I visit the http://localhost:8080 endpoint, and then edit the file. Then, if I edit again, my edits don't show up, but if I visit the endpoint, they do. And I guess that's perhaps what we might expect - live reload maybe needs something to trigger it, rather than running eagerly in the background? It will be interesting to see if live reload works when we have a unit test for the app. 

In any case, this is a handy workaround; it will be very useful for inspecting the bytecode coming out of the parser.

**Comment by hannotify** [comment]
Thanks for the update, @holly-cummins. It seems to me the discrepancy in behaviour is resoved, then. 
As for "Adding the .class extension", it turns out the compiled files already have the right extension, but IntelliJ IDEA probably hides them for class files. Because if I open the `target/classes` directory in Finder, I can see the actual .class extension.

So that still leaves "eagerly compiling". I tried adding a unit test in `rockstar-app`, but that yields a compilation failure when I run `mvn quarkus:dev`. Needs a bit more work!

**Comment by hannotify** [comment]
I checked the Kotlin extension to see how 'eagerly compiling' is supported there, and they use a dedicated Maven plugin (`kotlin-maven-plugin`) to bind a Kotlin compilation step to the `compile` phase. I don't think we should go that far, what are your thoughts on this @holly-cummins?

**Comment by holly-cummins** [comment]
I agree that a maven plugin is (a) a lot of work and (b) getting rather far from what we want to be showing. My first suggestion was 'maybe if we add a unit test that will trigger the compilation,' but you're there ahead of me, and no luck. I like your idea of doing it programmatically. I feel like rather than bundling a bean, a build item/step is more idiomatic, but [I don't see an obvious one](https://quarkus.io/guides/all-builditems). A build step that consumes an [ArchiveRoot](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/builditem/ArchiveRootBuildItem.java) might do the trick?

Although ... looking at the code, `https://github.com/quarkusio/quarkus/blob/02471b809f0ce693b570af057d287127d43defa9/core/deployment/src/main/java/io/quarkus/deployment/dev/testing/TestSupport.java#L53` does have a list of compilation providers, which to me says 'when running a test, compile things first'. Was your unit test a `@QuarkusTest`, @hannotify? Could you share it in a branch?

**Comment by hannotify** [comment]
Pushed the branch [fix/introduce-unit-test](https://github.com/holly-cummins/bon-jova-rockstar-implementation/tree/fix/introduce-unit-test), which has the unit test you asked for. The test fails initially, but succeeds after a .rock file has been edited at least once.

I put a few breakpoints in the Quarkus source code, but it seems like a `@QuarkusTest` annotated test class doesn't used the `TestSupport` class at all.

**Comment by holly-cummins** [comment]
Thanks! I've made a few little changes to the unit test class (more reflection), so it passes when the compilation happens. I've also put a few egregious hacks into the extension code, so the compilation happens. It's got too much my-machine-specific hardcoding to push, but once it's "portabl, but hideously hacky" rather than "totally unportable" I'll push to this branch, and we can go from there.
