### ISSUE TITLE
Add icon or emoji to the dev UI panel

### ISSUE THREAD

**Issue by holly-cummins** [holly-cummins/bon-jova-rockstar-implementation#12]
It would be cool to have the dev ui panel for the Rockstar extension show an icon. There's a few ways we could do this:

- Include the guitar emoji in the extension's display name
- Do something clever and custom and complicated (probably not worth it!)

There was some talk of the dev ui auto-display an icon based on the image metadata in the extension yaml, but I don't think that's been implemented yet.

**Comment by hannotify** [comment]
Added an emoji to the extension name.
