### ISSUE TITLE
Implement a better rock score

### ISSUE THREAD

**Issue by hannotify** [holly-cummins/bon-jova-rockstar-implementation#60]
Ideas for a better rock score:

* Curate a list of the best known (or the most popular) 80's rock songs.
* Build a list of the most common nouns in these songs.
* Assign a certain number of points to these nouns (the more common, the more points)
* Sum these points for each Rockstar program.
* Divide the sum by the sum of points for the top performing 80's rock song.
* Multiply by 100 and round to integer to get to the final score.
* Make sure the score can't get below `0` or above `100`.

**Comment by holly-cummins** [comment]
And, as a potentially longer term solution, https://docs.quarkiverse.io/quarkus-langchain4j/dev/index.html :)

**Comment by hannotify** [comment]
Proposed changes:

* Fetch the lyrics from an external source (a Lyrics API) so we don't have to store lyrics in the repository.
* Cache them in the `target/` directory to prevent unnecessary API calls.

**Comment by hannotify** [comment]
I completed the lyrics fetching. I'm proud to say I used Structured Concurrency to the max. 😄 

I still need to change the existing classes (`RockScoreCalculator`, `WordCounter` and `LyricsRatingCalculator`) so they'll use the downloaded lyrics instead of those currently in the repo. Will probably get to that tomorrow.
